imports:
  - { resource: 'providers.yml' }

security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            provider: in_memory
            http_basic: ~
#            form_login:
#                check_path: /login_check
#                login_path: /login
#            logout:
#                path:    /logout
#                target: /
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
            - { path: /admin, roles: ROLE_ADMIN }
            - { path: /, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
