services:
    yamlManager:
        class:        AppBundle\Service\YamlManager
    ofExtension:
            class: AppBundle\Twig\Extension\ofExtension
            tags:
                - {name: twig.extension}
    cvDownloadCounter:
        class: AppBundle\Service\CvDownloadCounter